version: "2"
services:
  web:
    image: nginx:1.18.0-alpine
    container_name: chrome_web
    ports:
      - 8084:80
    tty: true
    volumes:
      - "./html:/usr/share/nginx/html"
    restart: always